css/style.css

Home page About us Heading disappear on hover and description is not align properly

issue created

---

css/style.css

test issue

---

pahal.html

This is an attempt to resolve the issue no. 40 Video Embedding opened 4 days ago

Added embed link from Pahal Youtube video

---

pahal.html

This work has been done on the issue no. #39 Navbar is not sticky in Pahal Page

issue no #39

---

css/style.css

Event page description text color changed to white.

#19 resolved

---

event.html
nithvr.html

issue #21 => On clicking know-more button it should opens a model as it does in official site of Vibhav. @Event Page
issue #23 =>On the event page when clicked on a particular event, register here appears, remove it.
#23  must be solved before this. @Event Page

Resolved issue #21 and #23

---

projects.html

Attempt to solve issue no. 35 Styling (Project Card collor issue)

corrected the colors of the project cards

---

index.html

this pr is for resolving issue #9

discord link working issue #9

---

alumni.html

@nabin-nath ready for review!
Resolves #30 
Adds `_blank` target to links so they open up in new tab. I considered creating a link component, but tbh wasn't sure how to do that outside of React and javascript, so I thought this was the cleanest way. Here's a preview demonstrating the changes.

adds target to links to open in new tab

---

css/event.css

solved the issue #26

---

css/style.css
internexperience.html

this PR is in response to issue no #20 Link timing of the talk Intern Page

InternPage timestamps added to youTube links

---

css/style.css
internexperience.html

this pr is in response to the issue no 34 Make the Alumni page responsive
The issue was that with decreasing screen size the alumni Cards were shrinking 
resolved by adding appropriate cs
s

Alumni Page responsiveness added

---

css/style.css
internexperience.html

this pr is in response to the issue no 34  Make the Alumni page responsive and issue no  18 Navbar hover list item disappears Intern Experience Page
The issue was that with decreasing screen size the alumni Cards were shrinking for the alumni page
and for the intern page oh hovering on the dropdown list the items of the list were not visible 
resolved by adding appropriate css and removing redundant css for the files
s

CSS added for alumni page and intern page 

---

binary.html

Bug fixed team favicon visible #3

---

README.md

This pull request addresses Issue #66 (added "how should PR look like" in readme.md file.)
**Updated File:**

solved issue 66

---

index.html

Addressing issue Particlejs not working #13 
The background animation of Particlejs should now work as it should.

Fixed Particlejs

---

team.html

toggle button visible #24

---

diy.html

infinite preloader issue #11 resolved

Infinite preloader fixed #11

---

css/style.css

Addressing issue Navbar Toggle #38 .
The Navbar toggle is now visible and working on small viewports.

Fixed navbar Toggle

---

nithvr.html

This pull request addresses Issue #4  (**ISSUE:**  bit-n-byte should be inside games dropdown.)
**Before Update:**  bit-n-byte is not inside of drop-down of games
**After Update:**  Inserted the bit-n-byte inside the dropdown of game
.

solved issue #4 (added bit-N-byte in drop-down of games of nithvr file)

---

index.html
js/main.js

solved by  defining scroll to top button in index.html and then revising  code of that particular button in main.js file

#15 issue solved

---

team.html

Closes #29 
The carousel autoplay is now working and the number of images are same compared to official site.

Fixed Carousel autoplay

---

index.html

Issue #16 message button not working is fixed.

Changed Successfully

---

css/style.css

Transition of Vibhav Logo has been made as asked. Kindly review

#14 resolved 

---

alumni.html
css/style.css
diy.html
event.html
index.html
internexperience.html
nithvr.html
pahal.html
projects.html
team.html
workshop.html

#2 issue solved the-centinal

---

diy.html

footer added #12

---

css/button.css

#22 Intern Experience typewriter font animation 

---

alumni.html
diy.html
event.html
internexperience.html
nithvr.html
pahal.html
projects.html
team.html
workshop.html

Closes #6 .
Previous Behaviour : On navigating to any page via navbar its title was not active.
Updated Behaviour : Now its title on navbar as well as in the dropdown menu becomes active.

Added Active Class
